import Ctrl;
import FlxSpriteExt;
import LdtkProject;
import Lists;
import ProgressManager;
import SoundPlayer;
import Utils;
import actors.Actor;
import actors.Enemy;
import actors.Player;
import flixel.FlxBasic;
import flixel.FlxG;
import flixel.FlxObject;
import flixel.FlxSprite;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.math.FlxMath;
import flixel.math.FlxPoint;
import flixel.math.FlxRandom;
import flixel.math.FlxVelocity;
import flixel.util.FlxColor;
import states.BaseState;
import states.PlayState;
import ui.NGMedalPopUp;
#if html5
import NewgroundsHandler;
#end
